In [1]:
import numpy as np
import gym
import random

In [2]:
env = gym.make("Taxi-v2")

In [3]:
print(env.observation_space)

Discrete(500)


In [5]:
action_size = env.action_space.n
state_size = env.observation_space.n

In [6]:
qtable = np.zeros((state_size, action_size))
print(qtable)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 ...
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [8]:
total_episodes = 50000        # Total episode
learning_rate = 0.7           # Learning rate
max_steps = 99                # Max steps per episode
gamma = 0.618                 # Discounting rate

# Exploration parameters
epsilon = 1.0                 # Exploration rate
max_epsilon = 1.0             # Exploration probability at start
min_epsilon = 0.01            # Minimum exploration probability 
decay_rate = 0.01             # Exponential decay rate for exploration prob

state = env.reset()
env.render()
action = env.action_space.sample()
new_state, reward, done, info = env.step(action)

print(new_state)
env.render()
print(reward)

new_state

In [9]:
rewards = []
for episode in range(total_episodes):
    state = env.reset()
    step = 0
    done = False
    total_rewards = 0
    for _ in range(max_steps):
#         env.render()
#         print(state)
        exp_exp_tradeoff = random.uniform(0,1)
        if exp_exp_tradeoff > epsilon:
            action = np.argmax(qtable[state, :])
        else:
            action = env.action_space.sample()
        new_state, reward, done, info = env.step(action)
        qtable[state, action] = qtable[state, action] + learning_rate*(reward + gamma*np.max(qtable[new_state, :]) - qtable[state, action])
        total_rewards += reward
        state = new_state
        if done:
            break
    episode += 1
    epsilon = min_epsilon + (max_epsilon - min_epsilon)*np.exp(-decay_rate*episode)
    rewards.append(total_rewards)
print ("Score over time: " +  str(sum(rewards)/total_episodes))
qtable

Score over time: 6.80012


array([[  0.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   0.        ],
       [ -2.34172901,  -2.17107562,  -2.34172525,  -2.17329892,
         -1.89494435, -11.17107398],
       [ -0.72522586,   0.44475668,  -0.72871466,   0.4447696 ,
          2.33782249,  -8.55572998],
       ...,
       [ -2.01330095,   0.4446225 ,  -2.06537874,  -1.98071245,
         -7.        ,  -7.        ],
       [ -2.44268587,  -1.44813389,  -2.41153111,  -2.42344658,
        -10.84385793, -10.06620041],
       [ -0.7       ,  -0.7       ,  -0.91      ,  31.35602094,
         -7.        ,   0.        ]])

In [11]:
for episode in range(5):
    state = env.reset()
    step = 0
    done = False
    total_rewards = 0
    print("*****************")
    print("Episode ", episode)
    
    for _ in range(max_steps):
        action = np.argmax(qtable[state, :])
        new_state, reward, done, info = env.step(action)
        
        if done:
            env.render()
            if reward == 20:
                print("Successful!")
            break
        state = new_state
env.close()

*****************
Episode  0
+---------+
|R: | : :G|
| : : : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (Dropoff)
Successful!
*****************
Episode  1
+---------+
|R: | : :G|
| : : : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (Dropoff)
Successful!
*****************
Episode  2
+---------+
|R: | : :G|
| : : : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (Dropoff)
Successful!
*****************
Episode  3
+---------+
|R: | : :G|
| : : : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (Dropoff)
Successful!
*****************
Episode  4
+---------+
|R: | : :G|
| : : : : |
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
  (Dropoff)
Successful!
