In [52]:
import numpy as np
import gym
import random

In [53]:
env = gym.make("FrozenLake-v0")

In [54]:
print(env.observation_space)

Discrete(16)


In [55]:
action_size = env.action_space.n
state_size = env.observation_space.n

In [56]:
qtable = np.zeros((state_size, action_size))
print(qtable)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [57]:
total_episodes = 15000        # Total episode
learning_rate = 0.8           # Learning rate
max_steps = 99                # Max steps per episode
gamma = 0.95                  # Discounting rate

# Exploration parameters
epsilon = 1.0                 # Exploration rate
max_epsilon = 1.0             # Exploration probability at start
min_epsilon = 0.01            # Minimum exploration probability 
decay_rate = 0.005             # Exponential decay rate for exploration prob

state = env.reset()
env.render()
action = env.action_space.sample()
new_state, reward, done, info = env.step(action)

print(new_state)
env.render()
print(reward)

new_state

In [63]:
rewards = []
for episode in range(total_episodes):
    state = env.reset()
    step = 0
    done = False
    total_rewards = 0
    for _ in range(max_steps):
#         env.render()
#         print(state)
        exp_exp_tradeoff = random.uniform(0,1)
        if exp_exp_tradeoff > epsilon:
            action = np.argmax(qtable[state, :])
        else:
            action = env.action_space.sample()
        new_state, reward, done, info = env.step(action)
        qtable[state, action] = qtable[state, action] + learning_rate*(reward + gamma*np.max(qtable[new_state, :]) - qtable[state, action])
        total_rewards += reward
        state = new_state
        if done:
            break
    episode += 1
    epsilon = min_epsilon + (max_epsilon - min_epsilon)*np.exp(-decay_rate*episode)
    rewards.append(total_rewards)
print ("Score over time: " +  str(sum(rewards)/total_episodes))

Score over time: 0.46753333333333336


In [64]:
qtable

array([[1.87989685e-01, 1.27372049e-01, 9.50786987e-02, 1.29623169e-01],
       [3.60697512e-02, 3.31097245e-02, 2.03339862e-04, 1.44941186e-01],
       [1.37184022e-02, 3.52826291e-02, 3.53632791e-02, 1.04753232e-01],
       [7.34819865e-03, 1.22938586e-03, 1.36389369e-02, 7.93289184e-02],
       [4.76025853e-01, 8.19101550e-02, 3.19437672e-02, 2.30201688e-03],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [6.19198189e-05, 1.43833997e-04, 2.66902950e-01, 2.00311046e-07],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [2.57388311e-02, 9.87592422e-02, 7.11182674e-02, 4.90277836e-01],
       [2.84891166e-02, 1.15390562e+00, 8.81349948e-03, 4.19000305e-02],
       [1.61207368e+00, 4.83856494e-04, 3.75067031e-02, 1.65009293e-03],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [4.38904853e-02, 2.64013861e-01, 1.26595015e

In [68]:
for episode in range(5):
    state = env.reset()
    step = 0
    done = False
    total_rewards = 0
    print("*****************")
    print("Episode ", episode)
    
    for _ in range(max_steps):
        action = np.argmax(qtable[state, :])
        new_state, reward, done, info = env.step(action)
        
        if done:
            env.render()
            break
        state = new_state
env.close()

*****************
Episode  0
  (Down)
SFFF
FHFH
FFFH
HFFG
*****************
Episode  1
  (Down)
SFFF
FHFH
FFFH
HFFG
*****************
Episode  2
  (Right)
SFFF
FHFH
FFFH
HFFG
*****************
Episode  3
  (Down)
SFFF
FHFH
FFFH
HFFG
*****************
Episode  4
  (Down)
SFFF
FHFH
FFFH
HFFG


In [62]:
env.action_space

Discrete(4)